name: linting

on: [pull_request]
jobs:
  linting:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name:  Install Cppcheck
      run: sudo apt-get install -y cppcheck
    - name:  Run Cppcheck
      run: |
        cppcheck $GITHUB_WORKSPACE/firmware --enable=all  --force --template=gcc --inline-suppr --suppress-xml=$GITHUB_WORKSPACE/cppcheck/suppressions.xml -DSPEAKER_PIN -DCHARGER_PIN -DDISPLAY_U8G2_CONSTRUCTOR --output-file=report.txt 
        cat report.txt
    - name: Publish Report
      uses: actions/upload-artifact@v2
      with:
          name: cppcheck report
          path: report.txt


